<style>
    dt .bonus{
        display: inline-block;
        width:28px;
        line-height:32px;
    }
    dd{
        line-height:32px;
        padding-top:2px;
    }
    .bonus.f{
        background-color: #009587;
    }
    .bonus.r{
        background-color: #EC0000;
    }
    .bonus.s{
        background-color: #323F46;
    }
    .bonus.x{
        background-color: #384DB6;
    }
</style>
<h2>Controls</h2>
<dl>
  <dt><img src="assets/img/toucheDep.png" alt=""></dt>
  <dd>Move Gun</dd>
</dl>
<dl>
  <dt><img src="assets/img/rt.png" alt=""><span id="ou">/</span><img src="assets/img/toucheA.png" alt=""></dt>
  <dd>Fire</dd>
</dl>
<h2>Bonus</h2>
<dl>
    <dt><span class="bonus f">F</span></dt>
    <dd>Freeze concurrent</dd>
</dl>
<dl>
    <dt><span class="bonus r">R</span></dt>
    <dd>Rotate center</dd>
</dl>
<dl>
    <dt><span class="bonus s">S</span></dt>
    <dd>Reach the score</dd>
</dl>
<dl>
    <dt><span class="bonus x">X</span></dt>
    <dd>Self freeze</dd>
</dl>