<dl>
  <dt><img src="assets/img/toucheDep.png" alt=""></dt>
  <dd>Move Letter</dd>
</dl>
<dl>
  <dt><img src="assets/img/toucheA.png" alt=""></dt>
  <dd>Selected Letter</dd>
</dl>
<dl>
  <dt><img src="assets/img/toucheX.png" alt=""></dt>
  <dd>Delete Letter</dd>
</dl>
<dl>
  <dt><img src="assets/img/toucheY.png" alt=""></dt>
  <dd>How to play</dd>
</dl>
<dl>
  <dt><img src="assets/img/lb.png" alt=""></dt>
  <dd>Move Left</dd>
</dl>
<dl>
  <dt><img src="assets/img/rb.png" alt=""></dt>
  <dd>Move Right</dd>
</dl>
<dl>
  <dt><img src="assets/img/select.png" alt=""></dt>
  <dd>Come Back</dd>
</dl>
<dl>
  <dt><img src="assets/img/start.png" alt=""></dt>
  <dd>Validate</dd>
</dl>