<nav>
    <form action="post" id="formulaire">
        <div class="block">
            <div class="player">   
                <label>Joueur 1</label><span class="manette disconnected"></span>
                <input class="input-player" id="input-1" type="text" name="player-1"  disabled required>
                <span class="checked checked-1-2 hidden"></span>
                <span class="cursor hidden"></span>
            </div>
            <div class="player"> 
                <label>Joueur 2</label><span class="manette disconnected"></span>
                <input class="input-player" id="input-2" type="text" name="player-2"   disabled required>
                <span class="checked checked-3-4 hidden"></span>
                <span class="cursor hidden"></span>
            </div>
        </div>
        <div class="block">
            <div class="player">   
                <label>Joueur 3</label><span class="manette disconnected"></span>
                <input  class="input-player" id="input-3" type="text" name="player-3" disabled required>
                <span class="checked checked-1-2 hidden"></span>
                <span class="cursor hidden"></span>
            </div>
            <div class="player"> 
                <label>Joueur 4</label><span class="manette disconnected"></span>
                <input  class="input-player" id="input-4" type="text" name="player-4" disabled  required>
                <span class="checked checked-3-4 hidden"></span>
                <span class="cursor hidden"></span>
            </div>
        </div>
        <p>
            <input type="button" class="button gradian-blue" id="play" value="Lancer"/>
        </p>
    </form>
</nav>