<nav>
    <form action="post" id="formulaire">
        <div class="block">
            <div class="player">   
                <label>Joueur 1</label>
                <input class="input-player" id="input-1" type="text" name="player-1" autofocus="true" disabled required>
            </div>
            <div class="player"> 
                <label>Joueur 2</label>
                <input class="input-player" id="input-2" type="text" name="player-2"   disabled required>
            </div>
        </div>
        <div class="block">
            <div class="player">   
                <label>Joueur 3</label>
                <input  class="input-player" id="input-3" type="text" name="player-3" disabled required>
            </div>
            <div class="player"> 
                <label>Joueur 4</label>
                <input  class="input-player" id="input-4" type="text" name="player-4" disabled  required>
            </div>
        </div>
        <p>
            <input type="button" class="button gradian-blue" id="play" value="Lancer"/>
        </p>
    </form>
</nav>