<nav>
    <form action="post" id="formulaire">
        <div id="un-deux-player">
            <label class="name-player">Joueur 1</label>
            <input type="text" name="player-1" autofocus="true" required value="bernard"><br>
            <label class="name-player">Joueur 2</label>
            <input type="text" name="player-2" disabled value="maxime"><br><br>
        </div>
        <div id="trois-quatre-player">
            <label class="name-player">Joueur 3</label>
            <input type="text" name="player-3" disabled><br>
            <label class="name-player">Joueur 4</label>
            <input type="text" name="player-4" disabled><br><br>
        </div>
    </form>

    <a href="#" class="button valider" id="play">
        PLAY
    </a>
</nav>