<div id="scores-p1">
    <span class="name"></span>
    <span class="number"></span>
    <span class="findNumber"></span>
    <span class="level"></span>
</div>
<div id="scores-p2">
    <span class="name"></span>
    <span class="number"></span>
    <span class="findNumber"></span>
    <span class="level"></span>
</div>
<div id="scores-p3">
    <span class="name"></span>
    <span class="number"></span>
    <span class="findNumber"></span>
    <span class="level"></span>
</div>
<div id="scores-p4">
    <span class="name"></span>
    <span class="number"></span>
    <span class="findNumber"></span>
    <span class="level"></span>
</div>