 <table id="table">
     <thead>
        <tr>
            <th>Player</th>
            <th>Level</th>
            <th>Score</th>
            <th>stats</th>
        </tr>
    </thead>
    <tbody class="content">
        <tr id="stats-p1">
            <td class="name">...</td>
            <td class="level">...</td>
            <td class="score">...</td>
            <td class="stats">...</td>
        </tr>
        <tr id="stats-p2">
            <td class="name">...</td>
            <td class="level">...</td>
            <td class="score">...</td>
            <td class="stats">...</td>
        </tr>
        <tr id="stats-p3">
            <td class="name">...</td>
            <td class="level">...</td>
            <td class="score">...</td>
            <td class="stats">...</td>
        </tr>
        <tr id="stats-p4">
            <td class="name">...</td>
            <td class="level">...</td>
            <td class="score">...</td>
            <td class="stats">...</td>
        </tr>
    </tbody>
</table>